name:  WPF .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  

    env:
      Solution_Name: Visu.sln

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.3.4
    

    - name: Run the Cake build script
      uses: cake-build/cake-action@v1
      with:
        script-path: build.cake
          
    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
          name: setup.zip
          path: visu-app

    # Pack to ZIP
    - name: Packing output
      run: Compress-Archive -Path .\visu-app\ -DestinationPath setup.zip
        
    # Create release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: tagv0.1
          release_name: alpha-Release v0.1 ${{ github.ref }}
          draft: false
          prerelease: false
          
    # Upload binaries to release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: setup.zip
        asset_name: setup.zip
        tag: tagv0.1
        overwrite: true
