name:  WPF .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  

    env:
      Solution_Name: Visu.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16

    # Restore the WPF application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the WPF application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    # Execute Unit Tests
    - name: Execute Unit Tests
      run: dotnet test
        
    #Publish package (DOT NET CORE)
    - name: Publish
      run: dotnet publish .\Visu\Visu.csproj -c Release --self-contained --runtime win-x64 -o build\
        
      # Pack to ZIP
    - name: Packing output
      run: Compress-Archive -Path .\build\ -DestinationPath setup.zip
          
    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: setup.zip
        path: setup.zip
        
    # Create release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: tagv0.1
          release_name: alpha-Release v0.1 ${{ github.ref }}
          draft: false
          prerelease: false
          
    # Upload binaries to release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: setup.zip
        asset_name: setup.zip
        tag: tagv0.1
        overwrite: true
